name: C/C++ CI

on:
  push:
    branches: [ "gcc-11-support" ]
  pull_request:
    branches: [ "gcc-11-support" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./autogen.sh ; ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
